### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 2: invalid start byte

### ISSUE THREAD

**Issue by ninhhv** [D4-project/analyzer-d4-passivedns#2]
When I run command:  **python3 pdns-ingestion.py**
then display:
_2019-06-07 07:19:18,611 - pdns ingestor - INFO - Starting and using FIFO analyzer:8:ac45ea5c-be1b-46db-a0e1-50decb7d3c09 from D4 server
Traceback (most recent call last):
  File "pdns-ingestion.py", line 96, in <module>
    l = d4_record_line.decode('UTF-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 2: invalid start byte_

**Comment by gallypette** [comment]
Hi, interesting.
It looks like you are not feeding utf-8 do the analyzer, I have a bunch of questions:
- Can you tell me more about how you launch the passivedns client / on which system etc.?
- Is it failing systematically?
- Can you have a look in the D4-server web app and check the content of the redis queue?

**Comment by ninhhv** [comment]
- [ ] Can you tell me more about how you launch the passivedns client / on which system etc.?
I run on DNS server to stream DNS query to D4 server IP_D4_Server:
**sudo tcpdump -w - | /home/sysadmin/go/bin/d4-goclient -c /home/sysadmin/d4-goclient/conf.sample/ |  socat - OPENSSL-CONNECT:IP_D4_Server:4443,verify=0**
- [ ] Is it failing systematically?
System run ok, but I can't see result of analytic .
- [ ] Can you have a look in the D4-server web app and check the content of the redis queue? Yes, i can see queue number change every time.

**Comment by gallypette** [comment]
Alright I think I see the issue :)

Tcpdump should be sent using type 1 and then consumed using [analyzer-d4-pibs](https://github.com/D4-project/analyzer-d4-pibs ) (the only analyzer we have for type 1 ATM).

If you want to analyze dns, you should pipe DNS captures with gamelinux's [passivedns](https://github.com/gamelinux/passivedns):
```shell
sudo passivedns -i eth0 -l /dev/stdout | ./d4-amd64l -c conf.sample
```
^^ in the present example I leave the go client handling the TLS connection to the D4 server.

Small tip regarding the analyzer's redis queue: you can see the last elements in the queue when you click on the increasing number of elements.

You can check this [tutorial](https://d4-project.org/2019/05/28/passive-dns-tutorial.html) as it describes exactly what you are doing now.

**Comment by ninhhv** [comment]
Ok, thank you so much! Well done!
